export const ESubscriptions = {
  GAME_CREATED: "GAME_CREATED",
  GAME_CURRENT_STATE_CHANGED: "GAME_CURRENT_STATE_CHANGED",
  GAME_PLAYERS_CHANGED: "GAME_PLAYERS_CHANGED",
  PLAYER_ANSWERED: "PLAYER_ANSWERED",
};
