export const ESubscriptions = {
  GAME_CREATED: "GAME_CREATED",
  GAME_PLAYERS_UPDATED: "GAME_PLAYERS_UPDATED",
  GAME_STAGE_UPDATED: "GAME_STAGE_UPDATED",
  GAME_CURRENT_QUIZ_ITEM_UPDATED: "GAME_CURRENT_QUIZ_ITEM_UPDATED",
  PLAYER_ANSWERED: "PLAYER_ANSWERED",
};
